### ISSUE TITLE
undefined symbol: _ZN8casacore6python21register_convert_excpEv

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/LOFARBeam#21]
Not sure where to start to track this issue, this is from our installation in the Hamburg cluster when I try to load the stationresponse module from python

```
>>> from lofar import stationresponse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fdg/opt/lofar_200402/LOFARBeam/lib/python3.6/site-packages/lofar/stationresponse/__init__.py", line 23, in <module>
    from . import _stationresponse
ImportError: /home/fdg/opt/lofar_200402/LOFARBeam/lib/python3.6/site-packages/lofar/stationresponse/_stationresponse.so: undefined symbol: _ZN8casacore6python21register_convert_excpEv
```

I think this is related with:
casacore/python/Converters/PycExcp.cc

**Comment by mhardcastle** [comment]
What does `ldd /home/fdg/opt/lofar_200402/LOFARBeam/lib/python3.6/site-packages/lofar/stationresponse/_stationresponse.so` say?

**Comment by revoltek** [comment]
I think this was fixed by some magic of @tammojan  - shall we close the ticket?

**Comment by tammojan** [comment]
If it's not an issue for @revoltek  anymore let's close it.
