### ISSUE TITLE
cmake does not respect DPYTHON_EXECUTABLE

### ISSUE THREAD

**Issue by sarrvesh** [lofar-astron/LOFARBeam#24]
I am trying to build LOFARBeam with python3. When I run cmake with -DPYTHON_EXECUTABLE=/usr/bin/python3, cmake still finds the python2 interpreter (but finds the python3 library):

`-- Found PythonInterp: /usr/bin/python  `
`-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.2")`

and then fails with

`Compiling Python . support. If this is not the intended target use 'DPYTHON_EXECUTABLE' to control.`
`CMake Error at CMakeLists.txt:77 (if):`
`  if given arguments:`
``
`    "VERSION_LESS" "3"`

`  Unknown arguments specified`

Am I missing something?

**Comment by tammojan** [comment]
Could you try again (in a clean build dir) removing the file FindPython.cmake in lofarbeam/CMake?

**Comment by sarrvesh** [comment]
After deleting FindPython.cmake, it find the correct python version but I now get a new error. Not sure if it is related

-- Trying to find boost-python libraries with version suffix 38
Compiling Python 3.8 support. If this is not the intended target use 'DPYTHON_EXECUTABLE' to control.
-- Could NOT find Boost: missing: numpy38 (found /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.67.0"))
-- Falling back to old Boost search.
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.71.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

  Add the installation prefix of "boost_python3" to CMAKE_PREFIX_PATH or set
  "boost_python3_DIR" to a directory containing one of the above files.  If
  "boost_python3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:90 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by sarrvesh** [comment]
I fixed the boost issue. Now, in a clean build (CMake/FindPython.cmake deleted), I get the following error:

-- Found Python: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8") found components: Development 
Compiling Python . support. If this is not the intended target use 'DPYTHON_EXECUTABLE' to control.
CMake Error at CMakeLists.txt:77 (if):
  if given arguments:

    "VERSION_LESS" "3"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!

**Comment by sarrvesh** [comment]
Ah, found the solution. Installing libpython3-dev fixed the problem. Apologies for the noise. I'll close this ticket.

**Comment by toricolthurst** [comment]
How did you fix the boost issue? I'm stuck on this exact problem myself.

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.71.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

**Comment by Aviral1835** [comment]
-- Found NumPy: version "1.21.4" /usr/local/lib/python3.8/dist-packages/numpy/core/include
-- Using Python3
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.71.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

  Add the installation prefix of "boost_python3" to CMAKE_PREFIX_PATH or set
  "boost_python3_DIR" to a directory containing one of the above files.  If
  "boost_python3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:50 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/aviral/dex-net/deps/Boost.NumPy/build/CMakeFiles/CMakeOutput.log".
